### PR TITLE
Updated submitted.md to include raising an Issue in GitHub.

### PR DESCRIPTION
**Pull request by tejen**
See the following link to Tim Lee's CodePath documentation. Step #5 explains raising GitHub issues to submit work.
http://courses.codepath.com/snippets/intro_to_ios/

Raising an issue is necessary for all CodePath assignments (not just the prework assignment, of course).

### CODE REVIEW

**Comment by tejen** [comment]
Oh k, super cool! I noticed GitHub promotes the use of "\cc" on https://guides.github.com/features/issues/ so figured wouldn't hurt to use it.

Thanks for the info!!

**Comment by tejen** [comment]
Oh k, super cool! I noticed GitHub promotes the use of "\cc" on https://guides.github.com/features/issues/ so figured wouldn't hurt to use it.

Thanks for the pro tips, Katherine!!

**Comment by kmolo** [comment]
@tejen you're right.  Definitely makes it more human-readable to include \cc (or /cc ...which is correct, or if both what's the difference?)

I've seen many ways, but just wanted those in our CodePathU group to know that the '@username' was what was really flagging the Issue into the account of '@codepathreview'

Happy to see more contributors to this repo, by April it will really be awesome.

**Comment by tejen** [comment]
I see. I actually didn't even know that myself! Definitely a good thing to make it clear. Thanks a million!! :)

**Pull request merged**
